//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace attackcalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("attackcalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowser
        ///Captain Falcon
        ///Charizard
        ///Diddy Kong
        ///Donkey Kong
        ///Falco
        ///Fox
        ///Ganondorf
        ///Ice Climbers
        ///Ike
        ///Ivysaur
        ///Jigglypuff
        ///King Dedede
        ///Kirby
        ///Link
        ///Lucario
        ///Lucas
        ///Luigi
        ///Mario
        ///Marth
        ///Meta Knight
        ///Mewtwo
        ///Mr. Game &amp; Watch
        ///Ness
        ///Olimar
        ///Peach
        ///Pikachu
        ///Pit
        ///R.O.B.
        ///Roy
        ///Samus
        ///Sheik
        ///Snake
        ///Sonic
        ///Squirtle
        ///Toon Link
        ///Wario
        ///Wolf
        ///Yoshi
        ///Zelda
        ///Zero Suit Samus.
        /// </summary>
        internal static string characters {
            get {
                return ResourceManager.GetString("characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;settings&gt;
        ///  &lt;output&gt;
        ///    &lt;variables&gt;
        ///      &lt;var id=&quot;0&quot; enabled=&quot;true&quot;&gt;id&lt;/var&gt;
        ///	  &lt;var id=&quot;1&quot; enabled=&quot;true&quot;&gt;size&lt;/var&gt;
        ///	  &lt;var id=&quot;2&quot; enabled=&quot;true&quot;&gt;dmg&lt;/var&gt;
        ///	  &lt;var id=&quot;3&quot; enabled=&quot;true&quot;&gt;sdmg&lt;/var&gt;
        ///	  &lt;var id=&quot;4&quot; enabled=&quot;true&quot;&gt;angle&lt;/var&gt;
        ///	  &lt;var id=&quot;5&quot; enabled=&quot;true&quot;&gt;kbunits&lt;/var&gt;
        ///	  &lt;var id=&quot;6&quot; enabled=&quot;true&quot;&gt;bkb&lt;/var&gt;
        ///	  &lt;var id=&quot;7&quot; enabled=&quot;true&quot;&gt;wdsk&lt;/var&gt;
        ///	  &lt;var id=&quot;8&quot; enabled=&quot;true&quot;&gt;kbg&lt;/var&gt;
        ///	  &lt;var id=&quot;9&quot; enabled=&quot;true&quot;&gt;hitlagmulti&lt;/var&gt;
        ///	  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 118
        ///104
        ///110
        ///85
        ///114
        ///80
        ///75
        ///109
        ///88
        ///105
        ///85
        ///60
        ///112
        ///74
        ///104
        ///100
        ///80
        ///100
        ///100
        ///87
        ///79
        ///97
        ///75
        ///94
        ///90
        ///90
        ///80
        ///80
        ///104
        ///85
        ///110
        ///90
        ///105
        ///82
        ///82
        ///85
        ///107
        ///85
        ///108
        ///90
        ///85.
        /// </summary>
        internal static string weights {
            get {
                return ResourceManager.GetString("weights", resourceCulture);
            }
        }
    }
}
